[tool.poetry]
name = "iscc-sdk"
version = "0.6.0"
description = "SDK for creating ISCCs (International Standard Content Codes)"
authors = ["Titusz <tp@py7.de>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://sdk.iscc.codes"
repository = "https://github.com/iscc/iscc-sdk"
keywords=["iscc", "identifier", "media", "hash", "similarity"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Video",
    "Topic :: Scientific/Engineering :: Image Recognition",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Indexing",
]

[tool.poetry.urls]
"Changelog" = "https://sdk.iscc.codes/changelog"
"Coverage" = "https://app.codecov.io/gh/iscc/iscc-sdk"
"Bug Tracker" = "https://github.com/iscc/iscc-sdk/issues"
"Twitter" = "https://twitter.com/iscc_foundation"
"Donate" = "https://iscc.foundation/support"


[tool.poetry.scripts]
idk = 'iscc_sdk.cli:app'


[tool.poetry.dependencies]
python = ">=3.8,<4.0"
cython = "^0.29"
iscc-core = "^1.0"
iscc-schema = "^0.4"
python-magic-bin = { version = "^0.4", markers = "sys_platform == 'win32' or (sys_platform == 'darwin' and platform_machine == 'x86_64')" }
python-magic = { version = "^0.4", markers = "sys_platform == 'linux' or (sys_platform == 'darwin' and platform_machine == 'arm64')" }
install-jdk = "^0.3"
platformdirs = "^3.1"
jmespath = "^1.0"
Pillow = "^9.0"
pytaglib = "^2.0"
numpy = "^1.22"
pymupdf = "^1.21"
ebookmeta = "^1.2"
python-docx = "^0.8"
typer = {extras = ["all"], version = "^0.9.0"}


[tool.poetry.dev-dependencies]
pytest = "^7.0"
black = "^22.1"
coverage = "^7.0"
pytest-cov = "^4.0"
poethepoet = "^0.16"
bandit = "^1.7"
mkdocs-material = "^9.1"
mkdocstrings-python = "<1.1"
iscc-samples = "^0.6"
codetiming = "^1.3"
mdformat = "*"
mdformat_admon = "*"
mdformat_tables = "*"
griffe = "<0.27.4"

[tool.black]
skip-string-normalization = false
line-length = 100
target-version = ['py37']

[tool.coverage.run]
omit = ["iscc_sdk/install.py"]

[tool.poe.tasks]
docs = { cmd = "poetry run python -m devtools.build_docs", help = "Copy README.md to /docs" }
black = { cmd = "poetry run black .", help = "Code style formating with black" }
format-md = { cmd = "mdformat --wrap 100 README.md", help = "Markdown formating with mdformat" }
lf = { cmd = "poetry run python -m devtools.lf", help = "Convert line endings to lf"}
test = { cmd = "poetry run pytest --cov=iscc_sdk --cov-fail-under=100", help = "Run tests with coverage" }
sec = { cmd = "poetry run bandit -r iscc_sdk -q", help = "Security check with bandit" }
all = ["format-md", "docs", "lf", "black", "test"]

[build-system]
requires = ["poetry", "Cython"]
build-backend = "poetry.core.masonry.api"
